# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\github\BlindWatermark\GUI\main_win.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 845)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_2.setMaximum(2147483647)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox.setMaximum(399.99)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_2.setMaximum(399.99)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setMinimum(0)
        self.spinBox_3.setMaximum(2147483647)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 7, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setText("")
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setText("")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 5, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_6.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_6.addWidget(self.radioButton_2, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_6.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 12, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 3, 1, 1, 1)
        self.BlueProgressBar = QtWidgets.QProgressBar(self.tab)
        self.BlueProgressBar.setStyleSheet("#BlueProgressBar {\n"
"    border: 2px solid #2196F3;/*边框以及边框颜色*/\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0;\n"
"}\n"
"#BlueProgressBar::chunk {\n"
"    background-color: #2196F3;\n"
"    width: 10px; /*区块宽度*/\n"
"    margin: 0.5px;\n"
"}")
        self.BlueProgressBar.setProperty("value", 0)
        self.BlueProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.BlueProgressBar.setInvertedAppearance(False)
        self.BlueProgressBar.setObjectName("BlueProgressBar")
        self.gridLayout_4.addWidget(self.BlueProgressBar, 14, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setObjectName("listView")
        self.gridLayout_4.addWidget(self.listView, 1, 0, 12, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_5.setMinimum(4)
        self.spinBox_5.setMaximum(16)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_3.addWidget(self.spinBox_5, 2, 2, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_4.setMinimum(4)
        self.spinBox_4.setMaximum(16)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_3.addWidget(self.spinBox_4, 2, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_7.setMaximum(222222222)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_3.addWidget(self.spinBox_7, 1, 2, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_6.setMaximum(222222222)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_3.addWidget(self.spinBox_6, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 9, 1, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 4, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 11, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 6, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 8, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 280, 201))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_7)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_8.addWidget(self.textBrowser_2, 0, 0, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_8.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_8.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_8.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_3.setMaximum(1.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 0.7)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout.addWidget(self.doubleSpinBox_3)
        self.gridLayout_8.addWidget(self.frame_8, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(200, 180, 72, 15))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView.setGeometry(QtCore.QRect(400, 420, 256, 251))
        self.graphicsView.setStyleSheet("border-image: url(:/pic/setu_qrcode.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_2.setGeometry(QtCore.QRect(660, 360, 256, 371))
        self.graphicsView_2.setStyleSheet("border-image: url(:/pic/alipay.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(410, 350, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 891, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 410, 256, 251))
        self.graphicsView_3.setStyleSheet("border-image: url(:/pic/1563978351.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 370, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1044, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.help = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/question-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon)
        self.help.setObjectName("help")
        self.support = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/red envelope.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icon/red envelope.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.support.setIcon(icon1)
        self.support.setObjectName("support")
        self.menu_2.addAction(self.help)
        self.menu_2.addAction(self.support)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setToolTip(_translate("MainWindow", "推荐只填第一个, 数值大约为32左右, 在嵌入后图片与原图相似度可接受的前提下尽量取大"))
        self.label_2.setText(_translate("MainWindow", "量化因子"))
        self.label.setToolTip(_translate("MainWindow", "两个随机的整数即可"))
        self.label.setText(_translate("MainWindow", "随机种子"))
        self.frame_2.setToolTip(_translate("MainWindow", "从剪切板导入密钥, 同时修改下面的参数. 注, 点击左侧栏中的密钥可以将密钥放到剪切板中"))
        self.pushButton_2.setText(_translate("MainWindow", "导入水印"))
        self.pushButton.setText(_translate("MainWindow", "导入图片"))
        self.radioButton.setToolTip(_translate("MainWindow", "提取模式 , 只需在 导入图片 导入嵌入水印后的图"))
        self.radioButton.setText(_translate("MainWindow", "提取"))
        self.radioButton_2.setToolTip(_translate("MainWindow", "嵌入模式"))
        self.radioButton_2.setText(_translate("MainWindow", "嵌入"))
        self.checkBox_2.setToolTip(_translate("MainWindow", "勾选后会在同时输出嵌入水印后的图与原图的相识的参数"))
        self.checkBox_2.setText(_translate("MainWindow", "同时进行相似度验证"))
        self.pushButton_3.setText(_translate("MainWindow", "嵌入"))
        self.pushButton_4.setStatusTip(_translate("MainWindow", "在设置工作目录的前提下, 将原图和水印图复制到工作目录下"))
        self.pushButton_4.setText(_translate("MainWindow", "将图片复制到工作目录"))
        self.pushButton_11.setText(_translate("MainWindow", "打开工作目录"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "设置工作目录后,会在嵌入时在工作目录写入密钥: key.json"))
        self.pushButton_5.setText(_translate("MainWindow", "设置工作目录"))
        self.pushButton_6.setText(_translate("MainWindow", "从剪切板导入密钥"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "从key.json文件导入密钥, 并更新下来参数"))
        self.pushButton_7.setText(_translate("MainWindow", "从文件导入密钥"))
        self.label_10.setText(_translate("MainWindow", "未设置工作目录"))
        self.BlueProgressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_3.setText(_translate("MainWindow", "小波变换级数"))
        self.checkBox.setText(_translate("MainWindow", "限制相同"))
        self.label_7.setText(_translate("MainWindow", "水印形状"))
        self.label_6.setText(_translate("MainWindow", "分块形状"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "盲水印"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">恢复形变攻击</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">将经过平移,旋转,缩放,透视等形变的图片恢复成接近原图,是从受到形变攻击的图片中提取水印的必要前置步骤</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "读取原图"))
        self.pushButton_10.setText(_translate("MainWindow", "恢复"))
        self.pushButton_9.setText(_translate("MainWindow", "读取受到攻击的图片"))
        self.label_12.setText(_translate("MainWindow", "阈值:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "工具"))
        self.label_8.setText(_translate("MainWindow", "咕咕咕"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "盲水印抗破坏验证"))
        self.label_9.setText(_translate("MainWindow", "捐赠通道"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">菜逼程序员不会写那种可以弹出的帮助和关于界面</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">帮助部分:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">鼠标停在大多数元素上会有提示帮助的</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">左侧栏,密钥那一行点击可以把密钥放到剪切板上,图片那一栏点击可以查看图片</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">相似度参数解析:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">psnr在40以上是效果极好,在30~40为好,一般增大量化因子使其在30~40,可以保证较好的抗攻击能力和与原图较小的失真度</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">至于NCC值,越高表示效果越好,没找到相关指标, 反正保证略大于0.99就行</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">至于小波级数和分块大小,都是大一点好,小波级数一般取1~3,分块大小一般取4*4或者8*8 , 但是需要满足以下条件</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">设小波变换级数为d默认1,分块大小为(m,m)默认(4,4),图片大小为x * y ,水印的长宽乘积为wm_size,需满足</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/pic/gongshi.png\" /></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "请star一下我的github项目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "关于"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.help.setText(_translate("MainWindow", "帮助"))
        self.support.setText(_translate("MainWindow", "支持"))
        self.support.setToolTip(_translate("MainWindow", "恰饭"))


from img import sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
